#version 450

#include <libgpu/vulkan/vk/common.vk>

#include "../defines.h"

#pragma use_vulkan_memory_model

#extension GL_KHR_memory_scope_semantics : require
#extension GL_EXT_subgroup_uniform_control_flow : enable
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_KHR_cooperative_matrix : require
// Чтобы это компилировалось вам нужен достаточно свежий GLSL компилятор
// Например если вы получили ошибку "error: '#extension' : extension not supported: GL_KHR_cooperative_matrix"
// то вам потребуется его обновить, например для Linux:
// 1) wget https://github.com/google/shaderc/archive/v2025.4.zip
// 2) https://github.com/GPGPUCourse/GPGPUTasks2025/blob/05138f80f50c647845da6bc7c59878ac05576c06/scripts/linux/install_vulkan_sdk.sh#L73-L92
// Если потребуется - то явно указать путь к компилятору можно через CMake options: -DGLSLC_BIN=.../glslc.exe

layout(std430, binding = 0) readonly buffer MatrixAIn {
    fvec4 a[];
}; // rows=h x cols=k
layout(std430, binding = 1) readonly buffer MatrixBIn {
    fvec4 b[];
}; // rows=k x cols=w
layout(std430, binding = 2) buffer MatrixCOut {
    float c[];
}; // rows=h x cols=w

layout(push_constant) uniform PushConstants {
    uint w;
    uint h;
    uint k;
} params;

const uint LK = 16;
const uint KK = 4;

const uint WG_W_S = 4;
const uint WG_H_S = 2;

const uint WG_SS = WG_W_S * WG_H_S;
const uint INV_S = WG_SS * 32;

const uint C_RWS = 2;
const uint C_CLS = 2;

const uint TILE_M = LK * WG_H_S * C_RWS;
const uint TILE_N = LK * WG_W_S * C_RWS;
const uint TILE_K = LK * KK;

const uint A_RW_LEN = TILE_K;
const uint A_RW_NUM = TILE_M;

const uint B_RW_LEN = TILE_N;
const uint B_RW_NUM = TILE_K;

coopmat < float, gl_ScopeSubgroup, LK, LK, gl_MatrixUseAccumulator > result[C_RWS][C_CLS];

const uint VEC_SZ = 4;
const uint PAD = VEC_SZ;

shared fvec4 a_local[TILE_M * (TILE_K + PAD) / 4];
shared fvec4 b_local[TILE_K * (TILE_N + PAD) / 4];

uint coordToOffset(uint i, uint j, uint stride)
{
    return (stride * i + j);
}

layout(local_size_x = GROUP_SIZE, local_size_y = 1) in;
void main()
{
    uvec2 GID = gl_WorkGroupID.xy;
    uvec2 SGID = uvec2(gl_SubgroupID % WG_W_S, gl_SubgroupID / WG_W_S);

    #pragma unroll
    for (uint i = 0; i < C_RWS; ++i) {
        #pragma unroll
        for (uint j = 0; j < C_CLS; ++j) {
            result[i][j] = coopmat < float, gl_ScopeSubgroup, LK, LK, gl_MatrixUseAccumulator > (0.0);
        }
    }

    uint chkK = 0;

    const uint INVS_PER_RW_A = A_RW_LEN / VEC_SZ;
    const uint a_col_offset = VEC_SZ * (gl_LocalInvocationID.x % INVS_PER_RW_A);

    fvec4 a_reg[A_RW_NUM / (INV_S / INVS_PER_RW_A)];
    uint a_g_off = coordToOffset(TILE_M * GID.y, chkK, params.k);

    #pragma unroll
    for (uint i = 0; i < A_RW_NUM; i += INV_S / INVS_PER_RW_A) {
        uint a_row_offset = i + gl_LocalInvocationID.x / INVS_PER_RW_A;
        a_reg[i / (INV_S / INVS_PER_RW_A)] = a.x[(a_g_off + params.k * a_col_offset + a_row_offset) / VEC_SZ];
    }

    const uint INVS_PER_RW_B = B_RW_LEN / VEC_SZ;
    const uint b_col_offset = VEC_SZ * (gl_LocalInvocationID.x % INVS_PER_RW_B);

    fvec4 b_reg[B_RW_NUM / (INV_S / INVS_PER_RW_B)];
    uint b_g_off = coordToOffset(chkK, TILE_N * GID.x, params.w);
    #pragma unroll
    for (uint i = 0; i < B_RW_NUM; i += INV_S / INVS_PER_RW_B) {
        uint b_row_offset = i + gl_LocalInvocationID.x / INVS_PER_RW_B;
        b_reg[i / (INV_S / INVS_PER_RW_B)] =
            b.x[(b_g_off + params.w * b_col_offset + b_row_offset)];
    }

    for (uint chkK = 0; chkK < params.k; chkK += TILE_K) {
        bool last = (chkK + TILE_K) >= params.k;
        const uint strd_a_lc = (A_RW_LEN + PAD);

        barrier();
        #pragma unroll
        for (uint i = 0; i < A_RW_NUM; i += INV_S / INVS_PER_RW_A) {
            uint si = gl_LocalInvocationID.x / INVS_PER_RW_A;
            a_local[(strd_a_lc * si + a_col_offset) / VEC_SZ] = a_reg[i / (INV_S / INVS_PER_RW_A)];
        }

        const uint strd_b_lc = (B_RW_LEN + PAD);

        #pragma unroll
        for (int k = 0; k < A_RW_NUM; k += INV_S / INVS_PER_RW_B) {
            uint si = k + gl_LocalInvocationID.x / INVS_PER_RW_B;
            b_local[(strd_a_lc * si + b_col_offset) / VEC_SZ] =
                b_reg[k / (INV_S / INVS_PER_RW_B)];
        }

        barrier();

        uint a_g_off = coordToOffset(TILE_M * GID.y, chkK + TILE_K, params.k);
        #pragma unroll
        for (uint i = 0; i < A_RW_NUM; i += INV_S / INVS_PER_RW_A) {
            uint a_row_off = i + gl_LocalInvocationID.x / INVS_PER_RW_A;
            if (!last) a_reg[i / (INV_S / INVS_PER_RW_B)] = a.x[(a_g_off + params.k * a_col_offset + a_row_off) / VEC_SZ];
        }

        uint b_g_off = coordToOffset(chkK + TILE_K, TILE_N * GID.x, params.w);
        #pragma unroll
        for (uint k = 0; k < B_RW_NUM; k += INV_S / INVS_PER_RW_B) {
            uint b_row_off = k + gl_LocalInvocationID.x / INVS_PER_RW_B;
            if (!last) a_reg[k / (INV_S / INVS_PER_RW_B)] =
                    b.x[(b_g_off + params.w * b_col_offset + b_row_off) / VEC_SZ];
        }

        #pragma unroll
        for (int k = 0; k < TILE_K / LK; ++k) {
            uint sk = LK * k;
            coopmat < float16_t, gl_ScopeSubgroup, LK, LK, gl_MatrixUseA > mA[C_RWS];
            #pragma unroll
            for (uint i = 0; i < C_RWS; ++i) {
                uint si = LK * (C_RWS * SGID.y + i);
                coopMatLoad(mA[i], a_local, coordToOffset(si, sk, params.k) / VEC_SZ, params.k / VEC_SZ, gl_CooperativeMatrixLayoutRowMajor);
            }

            coopmat < float16_t, gl_ScopeSubgroup, LK, LK, gl_MatrixUseB > mB;
            #pragma unroll
            for (int j = 0; j < C_CLS; ++j) {
                uint sj = LK * (C_CLS * SGID.x + j);
                coopMatLoad(mB, b_local, coordToOffset(sk, sj, params.w) / VEC_SZ, params.w / VEC_SZ, gl_CooperativeMatrixLayoutRowMajor);

                #pragma unroll
                for (int i = 0; i < C_RWS; ++i) {
                    result[i][j] = coopMatMulAdd(mA[i], mB, result[i][j]);
                }
            }
        }
    }

    #pragma unroll
    for (uint i = 0; i < C_RWS; ++i) {
        uint gi = TILE_M * GID.y + LK * (C_RWS + SGID.y + i);
        coopmat < float, gl_ScopeSubgroup, LK, LK, gl_MatrixUseAccumulator > mC[C_CLS];

        #pragma unroll
        for (uint j = 0; j < C_CLS; ++j) {
            uint gj = TILE_N * GID.x + LK * (C_CLS * SGID.x + j);
            coopMatStore(result[i][j], c.x, coordToOffset(gi, gj, params.w), params.w, gl_CooperativeMatrixLayoutRowMajor);
        }
    }
}
